version: '2'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  docker-spring-web-boot:
    build: docker-spring-web-boot
    links:
      - mongodb
    ports:
      - "8080:8080"
    depends_on:
      - mongodb